Del project
duo-dinamico/CDM-FE pull request #9
Opened 2020-12-24 14:30 UTC by jcvsilva

New button in the project page, that will delete the project in the database.

2020-12-24 15:16 UTC, joaojesus81 requested changes
Few changes to make. Please address

2020-12-24 15:16 UTC, joaojesus81 commented on src/views/Project.vue
> +  <!-- <div class="delButton" @click="delProjectClick">Delete this project</div> -->
Remove commented line

2020-12-24 15:16 UTC, joaojesus81 commented on src/views/Project.vue
> +  setup(props, { emit }) {
Replace with:
`export default {
    props: [...],
    emits: ['reload'],`

2020-12-24 15:16 UTC, joaojesus81 commented on src/views/Project.vue
> +    };
Add Spinner component

2020-12-24 15:42 UTC, jcvsilva commented on src/views/Project.vue
> +  <!-- <div class="delButton" @click="delProjectClick">Delete this project</div> -->
Done.

2020-12-24 16:05 UTC, jcvsilva commented on src/views/Project.vue
> +  <!-- <div class="delButton" @click="delProjectClick">Delete this project</div> -->
Solved with commit: f91a260cf97436d69f11d6840cac0cff4c8ba3a6

2020-12-24 16:12 UTC, jcvsilva commented on src/views/Project.vue
> +  setup(props, { emit }) {
Solved with the merge of develop, commit: a95e07a5838412a71c17ff4d85b331bba1a7f46c

2020-12-24 16:17 UTC, jcvsilva commented on src/views/Project.vue
> +    };
Solved with the merge of develop, commit: a95e07a

2020-12-25 18:19 UTC, joaojesus81 approved these changes
Well done

2020-12-25 18:19 UTC, merged